### ISSUE TITLE
Server throws 500 (Internal STT Server Error)

### ISSUE THREAD

**Issue by berstend** [mozilla/speaktome-web#22]
Not sure if this is the right place but I didn't find a repo for the STT server itself.

When I'm trying the [web demo](https://mozilla.github.io/speaktome-web/) the server throws:
`{"error":"Internal STT Server Error"}`

Any idea why this might be, is the service discontinued?

**Comment by autonome** [comment]
Thanks for reporting! Let's poke the server people... @andrenatal?

**Comment by andrenatal** [comment]
I could not reproduce this error. Is it still failing for your guys? There's quite a lot of improvements we need to do to this API to comply to the latest server changes though.

**Comment by berstend** [comment]
Here's the test case:

```bash
❯❯❯ curl -XPOST 'https://speaktome-2.services.mozilla.com/' \
   -i -L \
   -H "Accept-Language-STT: en-US" \
   -H "Store-Sample: 0" \
   -H "Store-Transcription: 0" \
   --data-binary "@1.opus.ogg"
```

Response:
```
HTTP/1.1 100 Continue

HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Date: Wed, 09 Jan 2019 07:32:15 GMT
ETag: W/"25-tX3FYjOkjci40mUUeyoLl/P+zPc"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Powered-By: Express
Content-Length: 37
Connection: keep-alive

{"error":"Internal STT Server Error"}
```

Test file: https://www.dropbox.com/s/tayr9ygsb6a08p8/1.opus.ogg?dl=1

**Comment by berstend** [comment]
PPS: I don't think it's an encoding issue, e.g. when I try to upload a `.wav` file it throws correctly:

```bash
❯❯❯ curl -XPOST 'https://speaktome-2.services.mozilla.com/' \
   -i -L \
   -H "Accept-Language-STT: en-US" \
   -H "Store-Sample: 0" \
   -H "Store-Transcription: 0" \
   --data-binary "@1.wav"
HTTP/1.1 100 Continue

HTTP/1.1 400 Bad Request
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Date: Wed, 09 Jan 2019 07:35:36 GMT
ETag: W/"37-FSxEi+02iF1LMsPLeKGaOScBBYw"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Powered-By: Express
Content-Length: 55
Connection: keep-alive

{"message":"Body should be an Opus or Webm audio file"}
```

**Comment by andrenatal** [comment]
I think your audio file might be corrupted for some reason. Using the same command with the opus file we use for testing, it works fine:

`curl -XPOST 'https://speaktome-2.services.mozilla.com/' -i -L -H "Accept-Language-STT: en-US"     -H "Store-Sample: 0" -H "Store-Transcription: 0"     --data-binary "@speech_orig.opus"`

https://github.com/mozilla/speech-proxy/blob/master/speech_orig.opus

**Comment by rejas** [comment]
Any progress on this? I am encountering this error too (not always but a lot of times) when trying to get a little demo app running.

**Comment by autonome** [comment]
I see this error if:

* I send silence to the server
* If VAD picks up something that's not voice, and sends it to the server
